CREATE TABLE opd_registrations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    opd_uuid VARCHAR(36) NOT NULL UNIQUE,
    hospital_id BIGINT NOT NULL,
    patient_id BIGINT NOT NULL,
    doctor_id BIGINT,
    registration_date DATE NOT NULL,
    registration_time TIME NOT NULL,
    visit_type ENUM('NEW', 'FOLLOW_UP', 'REVIEW', 'EMERGENCY') DEFAULT 'NEW',
    token_number INT,
    vital_signs JSON,
    chief_complaints TEXT,
    diagnosis TEXT,
    treatment_plan TEXT,
    status ENUM('REGISTERED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED') DEFAULT 'REGISTERED',
    next_followup_date DATE,
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (hospital_id) REFERENCES hospitals(id) ON DELETE CASCADE,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (doctor_id) REFERENCES doctors(id),
    FOREIGN KEY (created_by) REFERENCES hospital_users(id),
    FOREIGN KEY (updated_by) REFERENCES hospital_users(id)
);

CREATE TABLE vital_signs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    opd_registration_id BIGINT NOT NULL,
    temperature DECIMAL(4,2),
    blood_pressure_systolic INT,
    blood_pressure_diastolic INT,
    heart_rate INT,
    respiratory_rate INT,
    oxygen_saturation DECIMAL(4,2),
    height DECIMAL(5,2),
    weight DECIMAL(5,2),
    bmi DECIMAL(4,2),
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    recorded_by BIGINT,
    FOREIGN KEY (opd_registration_id) REFERENCES opd_registrations(id) ON DELETE CASCADE,
    FOREIGN KEY (recorded_by) REFERENCES hospital_users(id)
);